sudo: false

addons:
  apt:
    packages:
    - curl
    - wget
    - oracle-java8-installer

language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

# Don't build branches/tags that match this regex. It's the convention used
# for tagging releases, which should be already tested before tagging.
branches:
  except:
    - /^v[0-9]/

env:
  global:
    - SWOOP_MAJOR_VERSION=2
    - SWOOP_RELEASE_BRANCH=swoop
    - SWOOP_PROJECT_VERSION="$SWOOP_MAJOR_VERSION.$TRAVIS_BUILD_NUMBER"

    # Maven info
    - secure: "K65paNwh3v8tobYVHPDiotwqtfz1yLjk8C+J8ch9alF4Z8ufufbh9w2Dq7SoMgbjHzb5K1QqdLQGXEcOfV2ri8JUYL9tI4tspXThPUFmpvbJ9rogbIQSAEolTiyblNRAMZ1WsH97daHBoT0UuYzyf/WEAEsybALT5d7Bz8oOiVEBJpyg0pa0qu/zUEYc4Uqljixf828ieLMzg0sBW97zAbkIeQvlZaTZ82xQWTocy6kSw+7wCnt3S8DGJqEv+bsJyaQvzVs8juxbzsJaFt5ddMPM905RpHKR1xk5hliMMKIRLq7oZ6fhQAN0JcDIq5MhG7kWDWDtAp8enyOgRZFgIcPK61ppdAAI95TSjS3i2zdeWxNg4wRWwPwQoipwd2bZppv1SGiis9lAgOIiIqKrIDbzTTaEOCDm+3hHIBc+yU2mTpW/i+BdAkMUU37mfjk9gvOPgy58cP7X7JLf5D/faGTrzEuDWuUP8vqE6gkEj3K6UgG7iw0rwGeH/XCbAxX+n2A9dgoLzFnEvkpQiwzV9Jaat9Y4380dV3nlXYLljMSuLGcvprspBl5UUe7sovZOcJ8UQEjeeH7/WxMTZ2pDQ5gbSX82Wcg4ZKOcu/yutQLC3Jn574dre6Za05AoR65xx8zGfwXWpFHM18/BBLHpy7iqxjWFmcLbbij1zPUImwU="
    - secure: "e3wEvVcXY+2wJe3mA2jYVOFANqaU53RpFKdcXz99PTfYGVjry/25+W3VJZIOhXNTHu3oXhkg/jAt5X2/IJ6+XDvMD3o61QE5cY9zNm0qmUcM4mI8Jx7CV2d76GS2CcAX/Jr27FzvXi70ryhvZl1J8iwbRlDYE80w0YX9sh4u6t27HKLSLXAWGLj8ZNtyU4jnIg5o9EJi9J3n8lHbny9kSLufZKKST6kCqX4UMii9RhffNxUzfoiD4OGJ88mz637bqhlFtKjkEGc4cFru3k1sHLsHLxdnxCOy4BHTHZm3+8Ly5WowYz7nGyNdGdoY2EfJ7eKVUUD0rM2Zz/vLXQ/SkSpuRpu7HLrXdkGpU2YFO3V8inUTA2LMWxH2oCOyFKjb/bTqsydrLoHk5T8+PKE33tVFTeHupTq4btv+3LpAbgatJbUbqaTysyaRDZK45oAGkN2LbyRG+k346cfXXqXH8FJSm4N1E3IcV0YIYLS0Qyq7Utgpuso5By3bvc9w5s7tyggGHapWRehli6PSvfC8840vjffJTDijYf/vskjLEZiY/OsBn1NhScTrlJV4jV0l/5KqTavEyXjTgzqzDRKFIHoRk8MyX5B7GdP/CfULt3h5n0SMr7mHzquIA1wo+oztx0c7KbX03IWiBwa1gNCRrA0dZjBLJ690b59s+ICY65Y="
    - secure: "Ke96YE3N67bnr9fZfQkBsINYiYNhD7pcyYSpkaHlPfcDUiV1Yc6vKdeFxCus25C6Je7J6QMAeUbUDvDQ/HEoEUw1HQWm+kQx3ShpdoC8GzyRVZgIU7QdWuD4lx8quOexuugbb5EFv2KRZJElhR06gm95qKM5IRibIK9svonQInjOgt/XBUoWBA4lAEBq4DBdj0aP9S+JEmRMF+Ip+Bq+oLkvB8+E3GvJmu6Gc+R6afHjQfnXr9G0DQ5QueKHUWdmNKYWsi4WIC1q/0or1cWsW9XHszyIAYYXGQLcMsn+zLhnwB55KI/IK5HQmvUIampVV07HQiTgUcjwmJhw7bOYBj9TPC3Oxry1L4GZEgs3J0NeVlpNmt9b/znw9AVQsu1aLcjafd6X5+LSZHJCqQd9ZxG6S2vICx63cLNKgRguDbqtJ00wUNxhIRtWgpLAyYen5i+qyzOLzdXSTMI0VDW6X5XblIQxyFHtcWmz3Rp8pWibKEDnjNsdhPHR17F2snBLoJGpaJyxsHg4ChCFjWa/skmmyqDSAxkeZUPD1i732/ILU47NpSzYKnqJOUwyH4JhE2XnlIDREsHEVSQha1Y+gOalWPJK+XjZXlwH7Ojx5TkgZp+xOw0yhwNLZu3hBvpSDppCKIvkR+V2AZ0Qxlbdpet3Ej8aHx3AoY/Ci1PjqHU="
    # Project specific IAM user
    - secure: "ROFRW2haSht7f22xiupY1LhtFuz+u5GZrVrZw8D4QYsk4VkK5s9zJJi14QXp/XXfzq4pIsLr68PjMSbTwGPL2eh9pAZ1lrAQBV729AZRHFPtwCvYi5Mq7vcFmjyAL/DRUxhrHNMrqUwnVatfC/bPerY+taRjKL0sVZ9tugkKNTlQYke/qyHBjx8iEELPpQMCAyBzxzDDRStdlamoSYayfWUOTqhMAWhUndwzU6IdLGFwtonk9PigZT68FbBWRJlXegZfMSZgfU74gXzltWYcJodJFdqxQzfo4/w6fMtuO4UC+VJNBc0uRxfmHK9nVA26eY14Rcx3S7UeVIvorcUrmVnA6xxKdBGMo1ETu3Jy6u66HvrgX2jMID/4IDDcb9tjP0LT8rcigKS7mqE5c0lS4OJkx7TGsp1MGroL6/IEs2GtNgowK8lo7hWfZ/I5ofLsbxPKuwi71I1lPUUKkz2HVmTn+IjIPdhFFxNYjBM3FTFsBAGmxl0xvfRDv8IfJXJ1E4V2BU03jSDR9W9MZuZmJuSOjudMn2mm6hJKkeDQseVqkhTVGCegMto04uIJdR7AIGVnc5JxcQ5tagqGz+X1MHwyA+vJ86GS1eZ79C+fvkTy8ZvAaxei5395wtvKLP39ImZR7Yttgp42V7r8NkNKci0zM8g3gamSFESo+D7Y0tg="
    - secure: "OuyFsjANp2hi96ZBeGxHrnOL9SGeBC/rWJbqBNKJKLrUDMY2xSrpzrlNLaFjTVKT7NsaJjTp2o34q6CtJ35DaHQg8ImitkMw/A7rAAoO7qbn5GBh4UiaZDVbcsGynDGYZcT3pCHIVDsSNBNzwszv+g6XHn14wqiPJHk8Y2V2q+QlEvv7SjYD37G4eETmdYH37nnmPVXlOT3ysn8ftpZZYf30n9uz1BMmvvk2ecYcPV+citVPTRlVesCSNHUJxrHBNRz8A2vAHrSfqvAvZ/ANRIIUYixcqdOHD2Pv04SbBwK8SSFSl7q21N+modf7kuWqyuPBuUA2JRYbGQIqYlS0pjhh0hBtnOfSoNX78qwsnPVBtDR4xaA0emd8kuHv0jKXJkVhym9TXDIz+tq9U/0cjGAkvl2Re/d0Qek8JAPL8xWmpCMLqZirjZzAoGVUv/wOqIzkR98pFa0FXHh7SKM3UTHmuV6olCn6YdiRkhJkvpIQSdIvta0n8M/ae/jiYgK+VK7rjSMnKz85jGd69T6LlRfOOeKA/MNCNH6608rL/jaWGDwG23KRG0OKEkKlOpWMuwh/Vwi51u41QgrN8uUsgzakVNfIiyr1DYerMCL+JlDHhIcL1CCt/3f3bv2d9mIxD9Hl2k9v+f656lx3GG5RLPkNhFq0bxlGGY+sm3THDI4="
    # Github access token for tagging releases
    - secure: "bGHXd/ju0ziHHRFwMbWd+My2K4eRVrvFb+0PrSV1eStH3cI6njRYb8PHf/oUf1ABxojsYwbMi5lr5xJfT8DBbaud4Mx+NOfjw+hVKYkzZxSysLONgIOQ5P251Adr1rCSumCtlCluGjkMUxlZn63BcndPkQKxLOwvnk6eFu+GBYumI2SX5YcKk4MZyHfFcuWYpd0pdEyfmzDWlxjDgS+XRva9ql+ZUqHaRn1Ze7iNB1rCjQKzPvYkX0k+x5sXRFxi2j08QWCG0g3s8auiqPHBXD8mH/VawkGGzQ1I9GeVk/du/XFswok0U6smnWJstzBq3YfJmqJaqLEAl4Cew7PR8nI6TwS363J+qBlnpgjrqUU0rg1BeAGc5Y7wAr9B46jtNRD9vzUzemSqDluWYI6jmZ2dyEKEGJ/bhvRe9cr6HYZ4lMnHv8E2LFJosqJAIzKKsURacC6YHTZUvidk3V9x1MfI20vIINXtzsrTUF3PXAt2UcSLiEySYhdg2k+AEtTqVtPe6q+/l+Fv+9noGExmfl2KC/jLijopicm9XJfq7XGGEj8NaS79s1s+qeIOF2Cxp9DE5Z4/rpU3R3e28luLS4XjyN/6jZJjgR2TsCYawFLgtwB1JkV9bhil8kNOvMlDLDlSnPnI65LCJGgIrAq+N/8WwCSBK622MB362dbTP2Q="

before_install: wget ${MAVEN_SETTINGS_URL} -O $HOME/.m2/settings.xml >/dev/null

install: mvn install -DskipTests

before_script:
  - >
    if [ ${TRAVIS_BRANCH} = ${SWOOP_RELEASE_BRANCH} ]
      then mvn versions:set -DnewVersion=${SWOOP_PROJECT_VERSION}
      else mvn versions:set -DnewVersion=${SWOOP_PROJECT_VERSION}-SNAPSHOT
    fi

script: mvn verify

after_success:
  # Maven deployments will always happen, but commits to anywhere other than
  # the designated release branch will be snapshot releases.
  - mvn -DskipTests=true deploy >/dev/null

  # On the specified release branch only, we'll tag in GitHub.
  - >
    [ ${TRAVIS_PULL_REQUEST} = 'false' -a ${TRAVIS_BRANCH} = ${SWOOP_RELEASE_BRANCH} ] &&
    curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${GITHUB_TOKEN}" -X POST "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/releases" -d '{
      "tag_name": "v'"${SWOOP_PROJECT_VERSION}"'",
      "target_commitish": "'"${TRAVIS_COMMIT}"'",
      "name": "v'"${SWOOP_PROJECT_VERSION}"'",
      "body": "https://travis-ci.org/'"${TRAVIS_REPO_SLUG}"'/builds/'"${TRAVIS_BUILD_ID}"'",
      "prerelease": false
    }'
